spring:
  datasource:
    url: jdbc:h2:mem:medicaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # can be create-drop, update, validate, none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: xKzCjYhp9j6harvwszuzCrtsRFTK51Tf
            client-secret: FBvbe5-4-Xyl6TMrvrJ6lkQPXX0ku-XSTTzlr_XkI35KGcl40JGDh0X6_XcB5ajZ
            scope: [openid, profile, email]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Auth0
        provider:
          auth0:
            issuer-uri: https://dev-1efg7uj5qgs527fo.us.auth0.com/
  mvc:
    #view:
    #  prefix: /
    #  suffix: .xhtml
    #static-path-pattern: /resources/**
    #web:
    #  resources:
    #    add-mappings: false
server:
  port: 8080
